name: "Run eslint with reviewdog"
description: "🐶 Run eslint with reviewdog on pull requests to improve code review experience."
author: "haya14busa (reviewdog)"
inputs:
  github_token:
    description: "GITHUB_TOKEN."
    required: true
  level:
    description: "Report level for reviewdog [info,warning,error]"
    default: "error"
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: "github-pr-check"
  eslint_flags:
    description: "flags and args of eslint command. Default: '.'"
    default: "."
  workdir:
    description: "The directory from which look for and run eslint. Default '.'"
    default: "."
  filter_mode:
    description: "The mode that reviewdog uses to filterr results. Default 'added'"
    default: "added"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "alert-octagon"
  color: "blue"
